name: CI / CD

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Frontend install
        working-directory: frontend
        run: npm ci

      - name: Frontend lint
        working-directory: frontend
        run: npm run -s lint

      - name: Frontend build
        working-directory: frontend
        run: npm run -s build

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore backend
        working-directory: backend/Freight.Api
        run: dotnet restore

      - name: Build backend
        working-directory: backend/Freight.Api
        run: dotnet build --configuration Release --no-restore

  docker:
    needs: ci
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Compute vars
        id: vars
        shell: bash
        run: |
          echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            jassra/myfreight:fe-${{ steps.vars.outputs.sha_short }}
            jassra/myfreight:fe-latest

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/Freight.Api
          file: ./backend/Freight.Api/Dockerfile
          push: true
          tags: |
            jassra/myfreight:be-${{ steps.vars.outputs.sha_short }}
            jassra/myfreight:be-latest
